table claims_predictions
	lineageTag: 79941194-4e8c-464a-99da-a070b5a21b67

	measure 'Total Policies' = COUNTROWS(claims_predictions)
		formatString: 0
		lineageTag: ffafcbe6-ce79-4e22-acc1-1352db6b4b0f

	measure 'Average Claim' = AVERAGE(claims_predictions[total_claim_amount])
		lineageTag: 26ea4cb2-1424-4400-84f6-dd8013998f48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Predicted Claim' = AVERAGE(claims_predictions[predicted_claim_amount])
		lineageTag: 7d1f386d-5cfc-4538-af8b-4bf6e9216b21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Risk Score' = AVERAGE(claims_predictions[risk_score])
		lineageTag: a72447f8-dee0-48bc-b8d7-2eb88c28abbc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: string
		lineageTag: 2e8ba6d2-534d-416c-9c23-e4e2bf17e041
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 40a9b678-b8d9-469a-b938-8070fb1caf81
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column customer_lifetime_value
		dataType: double
		lineageTag: b6a4ad09-0da6-4301-872c-7a7a7b067a5a
		summarizeBy: sum
		sourceColumn: customer_lifetime_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column response
		dataType: string
		lineageTag: 70ca5f70-f712-47a1-9212-d48f0b90c9f0
		summarizeBy: none
		sourceColumn: response

		annotation SummarizationSetBy = Automatic

	column coverage
		dataType: string
		lineageTag: 50a38c29-051f-456c-9d56-51870fc77adc
		summarizeBy: none
		sourceColumn: coverage

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 493b951c-f543-4a01-9850-2a3ee6674f49
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column effective_to_date
		dataType: string
		lineageTag: 296b15f3-ea17-4917-ace5-df76f7d871ec
		summarizeBy: none
		sourceColumn: effective_to_date

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 0b59caa6-4dc8-4a92-b048-ba3a21a14d2e
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 342042bc-0187-4de8-8cee-322f92a45cd7
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column income
		dataType: int64
		formatString: 0
		lineageTag: d417f35a-f684-4713-bcfd-fdca85cefa32
		summarizeBy: sum
		sourceColumn: income

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 03f540d1-99ad-49ce-82b9-5a316f42fb62
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: bae7a4d4-80ff-4d6c-a649-7c742673dab9
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column monthly_premium_auto
		dataType: int64
		formatString: 0
		lineageTag: a30aa4b2-f5ef-46da-a0bb-b44463f1b84d
		summarizeBy: sum
		sourceColumn: monthly_premium_auto

		annotation SummarizationSetBy = Automatic

	column months_since_last_claim
		dataType: int64
		formatString: 0
		lineageTag: c275dbb8-38b0-49b9-880e-0c1464d4c7e6
		summarizeBy: sum
		sourceColumn: months_since_last_claim

		annotation SummarizationSetBy = Automatic

	column months_since_policy_inception
		dataType: int64
		formatString: 0
		lineageTag: 70b0d34f-dc04-4c72-bd14-8a2b4ba84507
		summarizeBy: sum
		sourceColumn: months_since_policy_inception

		annotation SummarizationSetBy = Automatic

	column number_of_open_complaints
		dataType: int64
		formatString: 0
		lineageTag: 6cad6f9f-dc09-443b-88d2-76b5775350ca
		summarizeBy: sum
		sourceColumn: number_of_open_complaints

		annotation SummarizationSetBy = Automatic

	column number_of_policies
		dataType: int64
		formatString: 0
		lineageTag: 6de6540b-6136-4ca8-bb95-2c2c16552e2b
		summarizeBy: sum
		sourceColumn: number_of_policies

		annotation SummarizationSetBy = Automatic

	column policy_type
		dataType: string
		lineageTag: b7bdc69f-ee4e-417f-ba14-5cbc5002a0d5
		summarizeBy: none
		sourceColumn: policy_type

		annotation SummarizationSetBy = Automatic

	column policy_name
		dataType: string
		lineageTag: f661767b-aba6-415d-96d0-0e98cdd63ffe
		summarizeBy: none
		sourceColumn: policy_name

		annotation SummarizationSetBy = Automatic

	column renew_offer_type
		dataType: int64
		formatString: 0
		lineageTag: 882ce31f-02f5-4eb1-a0f5-f2ec6dea774c
		summarizeBy: sum
		sourceColumn: renew_offer_type

		annotation SummarizationSetBy = Automatic

	column sales_channel
		dataType: string
		lineageTag: 3c244f08-e60d-461c-b0e5-242448dc95c0
		summarizeBy: none
		sourceColumn: sales_channel

		annotation SummarizationSetBy = Automatic

	column total_claim_amount
		dataType: double
		lineageTag: fff77ff6-4dc8-4b18-9157-707ccb45414a
		summarizeBy: sum
		sourceColumn: total_claim_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vehicle_class
		dataType: string
		lineageTag: 5c6db02c-9ada-4ad0-a094-239297c96e69
		summarizeBy: none
		sourceColumn: vehicle_class

		annotation SummarizationSetBy = Automatic

	column vehicle_size
		dataType: string
		lineageTag: 3dac6d87-1d5a-47a7-9737-29cd0554ff1a
		summarizeBy: none
		sourceColumn: vehicle_size

		annotation SummarizationSetBy = Automatic

	column income_band
		dataType: string
		lineageTag: feb1b2a5-2a7a-4212-9681-e90e167a927a
		summarizeBy: none
		sourceColumn: income_band

		annotation SummarizationSetBy = Automatic

	column claim_severity
		dataType: string
		lineageTag: c4a09a67-52e8-46d2-a1a9-78fa7cf7ec95
		summarizeBy: none
		sourceColumn: claim_severity

		annotation SummarizationSetBy = Automatic

	column complaint_risk
		dataType: string
		lineageTag: 3858c78d-7d57-473e-b022-0a3659b8e140
		summarizeBy: none
		sourceColumn: complaint_risk

		annotation SummarizationSetBy = Automatic

	column risk_score
		dataType: int64
		formatString: 0
		lineageTag: ce241c44-f03f-4721-884b-a6ce8021a53b
		summarizeBy: sum
		sourceColumn: risk_score

		annotation SummarizationSetBy = Automatic

	column missing_income_flag
		dataType: int64
		formatString: 0
		lineageTag: 4b2cae1e-53d8-4e75-ba58-5a07a3249173
		summarizeBy: sum
		sourceColumn: missing_income_flag

		annotation SummarizationSetBy = Automatic

	column predicted_claim_amount
		dataType: double
		lineageTag: 88d8ddac-92b9-43d7-8921-9d8464167b6d
		summarizeBy: sum
		sourceColumn: predicted_claim_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_error
		dataType: double
		lineageTag: 3885ed6b-348e-49cb-8248-9064dc0cc4bf
		summarizeBy: sum
		sourceColumn: prediction_error

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition claims_predictions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ekw22\Downloads\insurance_project\claims_predictions.csv"),[Delimiter=",", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"state", type text}, {"customer_lifetime_value", type number}, {"response", type text}, {"coverage", type text}, {"education", type text}, {"effective_to_date", type text}, {"employment_status", type text}, {"gender", type text}, {"income", Int64.Type}, {"location", type text}, {"marital_status", type text}, {"monthly_premium_auto", Int64.Type}, {"months_since_last_claim", Int64.Type}, {"months_since_policy_inception", Int64.Type}, {"number_of_open_complaints", Int64.Type}, {"number_of_policies", Int64.Type}, {"policy_type", type text}, {"policy_name", type text}, {"renew_offer_type", Int64.Type}, {"sales_channel", type text}, {"total_claim_amount", type number}, {"vehicle_class", type text}, {"vehicle_size", type text}, {"income_band", type text}, {"claim_severity", type text}, {"complaint_risk", type text}, {"risk_score", Int64.Type}, {"missing_income_flag", Int64.Type}, {"predicted_claim_amount", type number}, {"prediction_error", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

